export const FETCH_GENRE_TYPES = "FETCH_GENRE_TYPES";

export const FETCH_GENRE_BY_ID_START = "FETCH_GENRE_BY_ID_START";
export const FETCH_GENRE_BY_ID_SUCCESS = "FETCH_GENRE_BY_ID_SUCCESS";

export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";

export const FETCH_MOVIE_START = "FETCH_MOVIE_START";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";

export const SEARCH_MOVIE_START = "SEARCH_MOVIE_START";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";

export const FETCH_CAST_START = "FETCH_CAST_START";
export const FETCH_CAST_SUCCESS = "FETCH_CAST_SUCCESS";
